/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AportarRouteImport } from './routes/aportar'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as RutasRouteImport } from './routes/rutas'
import { Route as ParqueIdRouteImport } from './routes/parque.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AportarRoute = AportarRouteImport.update({
  id: '/aportar',
  path: '/aportar',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const RutasRoute = RutasRouteImport.update({
  id: '/rutas',
  path: '/rutas',
  getParentRoute: () => rootRouteImport,
} as any)
const ParqueIdRoute = ParqueIdRouteImport.update({
  id: '/parque/$id',
  path: '/parque/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aportar': typeof AportarRoute
  '/favoritos': typeof FavoritosRoute
  '/rutas': typeof RutasRoute
  '/parque/$id': typeof ParqueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aportar': typeof AportarRoute
  '/favoritos': typeof FavoritosRoute
  '/rutas': typeof RutasRoute
  '/parque/$id': typeof ParqueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aportar': typeof AportarRoute
  '/favoritos': typeof FavoritosRoute
  '/rutas': typeof RutasRoute
  '/parque/$id': typeof ParqueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aportar' | '/favoritos' | '/rutas' | '/parque/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aportar' | '/favoritos' | '/rutas' | '/parque/$id'
  id: '__root__' | '/' | '/aportar' | '/favoritos' | '/rutas' | '/parque/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AportarRoute: typeof AportarRoute
  FavoritosRoute: typeof FavoritosRoute
  RutasRoute: typeof RutasRoute
  ParqueIdRoute: typeof ParqueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aportar': {
      id: '/aportar'
      path: '/aportar'
      fullPath: '/aportar'
      preLoaderRoute: typeof AportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rutas': {
      id: '/rutas'
      path: '/rutas'
      fullPath: '/rutas'
      preLoaderRoute: typeof RutasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parque/$id': {
      id: '/parque/$id'
      path: '/parque/$id'
      fullPath: '/parque/$id'
      preLoaderRoute: typeof ParqueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AportarRoute: AportarRoute,
  FavoritosRoute: FavoritosRoute,
  RutasRoute: RutasRoute,
  ParqueIdRoute: ParqueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
